# _____DEIN LAZY TOML_____ {{{


[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 0
    let g:deoplete#auto_complete_start_length = 1
    let g:deoplete#enable_camel_case = 0
    let g:deoplete#enable_ignore_case = 0
    let g:deoplete#enable_refresh_always = 0
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#file#enable_buffer_path = 1
    let g:deoplete#max_list = 10
    inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
    nnoremap <silent><Space>d :call deoplete#toggle()<CR>
'''

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_add = '''
    if has('conceal')
      set conceallevel=2 concealcursor=niv
    endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''
    let g:neosnippet#snippets_directory = '~/.config/nvim/snippets/'
'''

[[plugins]]
repo = 'Yggdroot/indentLine'                                                
hook_add = '''
    let g:indentLine_faster = 1
    let g:indentLine_char = '┆'
'''

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python', 'ruby', 'c', 'cpp', 'java', 'html', 'js', 'sass', 'php', 'sql']
hook_add = '''
    let g:ale_enabled = 0
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'neovim/python-client'

# ___Compile___ {{


# C , C++

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']
hook_add = '''
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-4.0/lib/libclang-4.0.so.1'
    let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''


# }}


# ___Script___ {{

# Python

[[plugins]]
repo = 'davidhalter/jedi'
on_ft = 'python'
hook_add = '''
setlocal completeopt-=preview
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'


# Ruby

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

# }}


# ___Web___ {{

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'sass']

# php

[[plugins]]
repo = 'padawan-php/deoplete-padawan'
on_ft = 'php'

# js

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'js'

# }}


# Toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

#[[plugins]]
#repo = 'ujihisa/neco-look'


# }}}
